### ISSUE TITLE
Two issues - Awaiting handler not working & SwipeNestedAction not closing when calling handler(false)

### ISSUE THREAD

**Issue by naamapps** [luckysmg/flutter_swipe_action_cell#24]
Hey,
I have found 2 issues.
1. Awaiting the handler doesn't seem to work, I call handler(false) because I have my own animation when removing items from the list, but I want my animation to run after the slidable is closed. So I need to await the handler but its not waiting.
2. SwipeNestedAction is not closing (stays in place) when calling handler(false) on tap. As I said, I have my own animations so when removing something from the list the nested action just stays there without closing. Need to point out that I have a custom content in all of the SwipeActions including the SwipeNestedAction (exactly like your example in the [readme](https://github.com/luckysmg/flutter_swipe_action_cell#example-7customize-shape)).

Thanks!

**Comment by luckysmg** [comment]
I think I have fixed the two issues you mentioned in https://github.com/luckysmg/flutter_swipe_action_cell/commit/511fe3fbd3aad8ffb09e9c7152d8954749eee45d

you can try this ref using code below first,and if there is no problem,I will push it to pub.dev,hoping your response
```yaml
flutter_swipe_action_cell:
    git:
      url: 'https://github.com/luckysmg/flutter_swipe_action_cell.git'
      ref: '511fe3fbd3aad8ffb09e9c7152d8954749eee45d'
```
